### ISSUE TITLE
Please add example callback definition on new message event

### ISSUE THREAD

**Issue by vad11** [yaroslavche/phptdlib#75]
Please add example callback php script definition on new message event.

**Comment by yaroslavche** [comment]
Seems to me that you should try [getChatHistory](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1get_chat_history.html) and compare with latest known messages on your side (which, I suppose, are received also with getChatHistory). But maybe I'm wrong. Personally I don't use tdlib and don't know how to solve this kind of tasks with tdlib API.
Extension provides:
 - `td_json_client_create`
 - `td_json_client_execute`
 - `td_json_client_send`
 - `td_json_client_receive`
 - `td_json_client_destroy`
, so feel free to use as you want.

Issue will be closed, since it's not related to this extension and depends on workflows, where and how this extension should be used.
