### ISSUE TITLE
importContacts causes an error

### ISSUE THREAD

**Issue by hhsnake** [yaroslavche/phptdlib#81]
Hello, i have compiled latest PHP-CPP v2.0.0 and phptdlib

when i invoke importContacts i get error

`
    $addContact = $client->query(json_encode(['@type' => 'importContacts', 'contacts' => [
        [
            'phone_number' => '+12133123456',
        ],
    ]]));
    var_dump(json_encode($addContact));
`

"{\"@type\":\"error\",\"code\":429,\"message\":\"Too Many Requests: retry after 3600\",\"@extra\":xxxx}"

but next line is invoke without error

`
    $getMe = $client->query(json_encode(['@type' => 'getMe']));
    var_dump(json_encode($getMe));
`

"{\"@type\":\"user\",\"id\":xxxxx,\"first_name\":\"......

when i try 

`
    $addContact = $client->query(json_encode(['@type' => 'importContacts', ['contacts' => [
        [
            'phone_number' => '+12133942853',
        ],
    ]]]));
    var_dump(json_encode($addContact));
`

"{\"@type\":\"importedContacts\",\"user_ids\":[],\"importer_count\":[],\"@extra\":xxxx}"

Could you suggest the correct call to the importContacts function or there may be an error in something else.

**Comment by yaroslavche** [comment]
"message":"`Too Many Requests`: retry after `3600`" . Maybe this is an API limitations with `importContacts` method, IDK. I can suggest just wait if you face this error again. Or maybe somehow handle it in code.

**Comment by hhsnake** [comment]
I showed in the example that immediately after the call to 'importContacts', the 'getMe' is called and it does not have to wait.
Importing a single contact cannot result in 'Too Many Requests'. Could you reproduce my error on your own?

**Comment by yaroslavche** [comment]
Sorry, but I can't right now, I don't have installed extension. Anyway, looks like this is question for [tdlib/td](https://github.com/tdlib/td), because phptdlib haven't any limitations, and if you faced one (no matter where, when and why) - then I don't know why, it's on tdlib side, not on this extension. Phptdlib just send requests and receive responses, that's all. If you able to receive responses via phptdlib - then for further information about how need to use you should use TDLib docs and support

**Comment by hhsnake** [comment]
Thank fo replay, it's strange, I tried to send requests for 3 days, I got an error, today the service returned a response

'"{\"@type\":\"importedContacts\",\"user_ids\":[xxxx,xxxx,xxxx],\"importer_count\":[0,0,0],\"@extra\":xxx}"
